### PR TITLE
CSRF Exemption Removed

### PR DESCRIPTION
**Pull request by jmons**
This has a new set of tests specifically to look at issue #14, but even with the `@csrf_exempt` decorator removed, I can't find any issues.

I don't think this is needed for a release right now, but I would like to merge it in ready for whatever feature comes next.

### CODE REVIEW

**Comment by jmons** [comment]
Ooh now that's interesting, because I ran all the tox tests before committing and pushing (screen grab from local tox:

screen shot 2017-03-28 at 23 21 03

I will have to look at this later.

**Comment by Jamian** [comment]
I gave tox a run locally and get fails for py27-django7 and p3-django7...

Not sure how your local ran fine.

image

**Comment by jmons** [comment]
Ok, if I force tox to reload its cache (`tox -r`) then this now fails on my local machine. I wonder if django7 is now a broken install?

**Comment by jmons** [comment]
Dave has graciously found the cause - there is a django change (the builds worked fine for him on his mac) so I'm going to reverse-merge again, and re-run the tests.

**Comment by jmons** [comment]
Closing as not part of RC2 structure: this code has been completly re-written.

**Pull request closed without merging**
